version: '3'
services:
  caddy:
    restart: always
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - 80:2015
    networks:
      - caddy
    command: -email assada.ua@gmail.com -agree=true -log stdout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./app:/var/www
      - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - caddy
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - caddy
    labels:
      caddy.address: 3ds.kill.guru
      caddy.targetport: "80"
      caddy.tls: "on"

networks:
  caddy:
    external:
      name: assada-services